- hosts: devbox
  name: Setup Dev Box
  remote_user: ubuntu
  become: yes
  vars:
    ssh_keys_url: https://github.com/joeunrue.keys
    git_username: joeunrue
    git_email: saxon@unrue.com
    username: saxon
  roles:
    - { role: 'common', tags: 'common' }
    - { role: 'webdev', tags: 'webdev' }
    - { role: 'springbot', tags: 'springbot' }
