- name: Clone rbenv repository
  git: repo=https://github.com/rbenv/rbenv.git
       dest=~{{ username }}/.rbenv
       update=no

- name: Set correct owner and group
  file: path=~{{ username }}/.rbenv
        owner={{ username }}
        group={{ username }}
        recurse=yes

- name: Install rbenv loader script
  copy:
    src: "{{ role_path }}/files/rbenv.sh"
    dest: /etc/profile.d/rbenv.sh

- name: "Install Necessary Packages"
  apt: name={{item}} state=present update_cache=yes
  with_items:
    - bzip2
    - gcc
    - make
    - autoconf
    - bison
    - build-essential
    - libssl-dev
    - libyaml-dev
    - libreadline6-dev
    - zlib1g-dev
    - libncurses5-dev
    - libffi-dev
    - libgdbm3
    - libgdbm-dev
    - git

- name: Clone ruby-build
  git: repo=https://github.com/rbenv/ruby-build.git
       dest=~{{ username }}/.rbenv/plugins/ruby-build
       update=no

- name: Set correct owner and group
  file: path=~{{ username }}/.rbenv/plugins/ruby-build
        owner={{ username }}
        group={{ username }}
        recurse=yes

- name: "Install postgres"
  apt: name={{item}} state=present update_cache=yes
  with_items:
      - postgresql
      - postgresql-contrib
      - libpq-dev

- name: "Install pip and virtualenv"
  apt: name={{item}} update_cache=yes
  with_items:
      - python3-pip
      - python-pip
      - virtualenv
