---
- name: "Install Necessary Packages"
  apt: name={{item}} state=present update_cache=yes
  with_items:
      - automake
      - pkg-config
      - openssh-server
      - git
      - htop
      - curl
      - wget
      - tree
      - python3-psycopg2
      - python-psycopg2

- name: "Install Software Dependencies to allow use of add-apt-repository"
  apt: name={{item}} state=present
  with_items:
      - software-properties-common
      - python-software-properties

- name: "Create User {{username}}"
  user:
    name: "{{username}}"
    shell: /bin/bash
    groups: sudo
    append: yes
    system: yes
    home: "/home/{{username}}"
    state: present
  notify: fix home folder permissions

- name: "Add user to the sudoers"
  raw: echo '%sudo	ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

- name: "Add authorized keys"
  authorized_key:
    user: "{{username}}"
    state: present
    key: "{{ssh_keys_url}}"

- name: "Install zsh"
  apt: name={{item}} state=present update_cache=yes
  with_items:
      - zsh

- name: "Change shell to zsh"
  user: name={{username}} shell=/bin/zsh
  become: true

- name: "Download thoughtbot dotfiles"
  become: yes
  become_user: "{{username}}"
  git:
    repo: https://github.com/thoughtbot/dotfiles.git
    dest: "/home/{{username}}/dotfiles"
    clone: yes
    force: yes

- name: "Download my local dotfiles"
  become: yes
  become_user: "{{username}}"
  git:
    repo: https://github.com/{{git_username}}/dotfiles-local.git
    dest: "/home/{{username}}/dotfiles-local"
    clone: yes
    force: yes

- name: "Add rcm repo"
  apt_repository:
    repo: ppa:martin-frost/thoughtbot-rcm

- name: "Install rcm"
  apt:
    name: rcm

- name: "Install my dotfiles"
  become: yes
  become_user: "{{username}}"
  command: "env RCRC=$HOME/dotfiles/rcrc rcup"

- name: "Install Vundle"
  git:
    repo: https://github.com/VundleVim/Vundle.vim.git
    dest: "/home/{{username}}/.vim/bundle/Vundle.vim"
    clone: yes

- name: "Add vim 8 PPA"
  apt_repository:
    repo: 'ppa:jonathonf/vim'

- name: "Install vim 8 (with python3 support)"
  apt: name={{item}} state=present update_cache=yes
  with_items:
    - vim
    - vim-nox

- name: "Install Tmux 2.2+ Dependencies"
  apt: name={{item}} state=present update_cache=yes
  with_items:
      - libevent-dev
      - libncurses-dev
      - build-essential

- name: "Install tmux"
  apt:
    name: tmux
